// Research copy is grounded in the user's November 2023 interview slides,
// January 2024 concept-test report, and the existing portfolio's product data.
// Concept feedback describes acceptance, not measured task success or shipped features.
export const healthChatbotCase = {
  zh: {
    subtitle: '讓健康疑問，更容易成為第一個 AI 提問',
    intro: '健康 2.0 App 推出 AI Chatbot 後，服務使用率僅佔整體的 2%。我結合提問紀錄、使用者訪談與概念測試，釐清使用者如何理解 AI、何時需要健康資訊，再將研究轉為兩個設計方向：App 內的建議提問，以及 Web 健康文章中的延伸問答。',
    date: '2023–2024',
    summary: [
      { label: '用戶研究', value: '7 位訪談\n6 位概念測試', mobileValue: '7 位訪談\n6 位測試', description: '兩輪研究，找出提問門檻' },
      { label: '解法', value: 'App 建議提問\nWeb 文章延伸問答', mobileValue: 'App 引導\nWeb 問答', description: '降低開始提問的門檻' },
      { label: '成效', value: '9k → 27k', description: 'AI Chatbot 使用量成長', mobileDescription: '使用量成長' },
    ],
    goal: '提升 AI Chatbot\n服務使用率',
    navigation: [['problem', '問題與數據'], ['interviews', '第一輪訪談'], ['concept-test', '第二輪測試'], ['decisions', '設計決策'], ['outcomes', '成效與反思']],
    problemTitle: '有健康資訊需求，卻不一定會向 AI 提問',
    problemCopy: '低使用率只是問題的起點。我先檢視上線後的提問紀錄：使用者輸入的是完整問題、身體狀況，還是單一症狀？這份分析用來辨識輸入行為，再透過訪談了解背後原因。',
    dataInsight: '模糊描述與症狀關鍵字合計約 54%。不少輸入尚未形成完整問題，提示我們需要協助使用者表達需求；但紀錄本身無法解釋未使用 AI 的原因。',
    dataNote: '資料沿用原專案提問紀錄，共 20,350 筆事件；事件數不等於使用者人數。各類佔比經四捨五入，合計可能略高於 100%。',
    baselineNote: '2% 為原專案記錄的 App 服務使用率；與後續 Web 文章參與率分屬不同指標。',
    dataSummary: '查看提問分類與事件數',
    tableHead: ['提問類型', '輸入內容', '事件數', '佔比'],
    data: [
      ['完整健康問題', '以完整句子描述症狀、情境或直接提出問題。', '8,482', '41.7%', 41.7],
      ['模糊健康描述', '描述狀況但沒有明確問題，例如「長期壓力大」、「一直睡不好」。', '6,282', '30.9%', 30.9],
      ['健康主題／症狀關鍵字', '只輸入疾病或症狀名稱，例如「頭痛」、「糖尿病」。', '4,683', '23.0%', 23],
      ['非健康相關文字', '打招呼、感謝、聊天或其他與健康無關的內容。', '791', '3.9%', 3.9],
      ['空白輸入', '未輸入任何內容。', '112', '0.6%', .6],
    ],
    interviewTitle: '先了解健康行為，再辨識對 AI 的期待與疑慮',
    interviewCopy: '第一輪訪談涵蓋不同健康狀態與健康促進行為的使用者，了解他們對既有 AI Chatbot 的看法。從回饋中區分功能認知、提問起點與回答信任三個問題，作為下一輪概念探索的依據。',
    timeline: [['11/17–11/20', '招募'], ['11/20–11/24', '使用者訪談'], ['11/27–12/01', '整理與分析']],
    interviewMeta: [['研究時間', '2023 年 11 月'], ['參與者', '7 位，35–68 歲'], ['行為分組', '主動健康促進 3 位／被動 4 位'], ['健康狀態', '健康 2 位／亞健康 2 位／疾病 3 位']],
    interviewLabel: '訪談摘要',
    interviewFindings: [
      ['AI 有補位的價值', '受訪者提到半夜無法詢問真人時，至少可以向 AI 尋求資訊。', '機會：在需要即時資訊的情境中，AI 可以成為可取得的入口。'],
      ['入口與提問範圍不清楚', '回饋包含不知道有此功能、不知道該問什麼，以及不理解 AI Chatbot／ChatGPT 是什麼。', '問題：使用前需要先理解服務用途，並看見具體的提問起點。'],
      ['回答品質影響信任', '有使用經驗的受訪者覺得回答制式，仍偏好直接詢問真人。', '限制：降低提問門檻之外，仍需關注回覆的實用性與可信度。'],
    ],
    researchBridge: '下一輪要驗證：如果換成更具體的角色、提問範例或熟悉的問答情境，使用者是否更能理解 AI 可以提供什麼幫助？',
    conceptTitle: '比較 AI 服務的不同形式，找到容易理解的切入點',
    conceptCopy: '第二輪以「個人健康管理」為主題，透過 Prototype 與訪談探索不同功能提案的接受度、預期用途與回饋。研究範圍包含健康紀錄、提醒、主動關心、不同 AI 角色、群聊、QA 討論版、健康目標及搜尋／提問入口。',
    conceptMeta: [['測試時間', '2024/01/13–01/23'], ['參與者', '6 位，37–68 歲'], ['健康狀態', '亞健康 3 位／疾病 3 位'], ['產品經驗', '使用過健康 2.0 App 3 位／未使用 3 位']],
    conceptTableHead: ['測試形式', '使用者回饋', '對設計的意義'],
    concepts: [
      ['個人化紀錄、提醒與關心', '沒有紀錄習慣者，不會只因對話更方便就開始記錄；比起關心語，更想看到實際改善方式。', '先呈現有用的資訊與建議，避免把功能便利等同於使用動機。'],
      ['不同 AI 角色', '多數人可從角色名稱與介紹理解用途，並期待運動教學、菜譜等相應內容。', '具體用途有助理解服務；角色也會帶來主動提供內容的期待。'],
      ['主題群聊＋AI', '多數人群聊意願不高，傾向看別人討論，也擔心討論缺乏專業性。', '不能把加入聊天視為尋找健康資訊的必經步驟。'],
      ['QA 討論版＋AI', '報告記錄全體 6 位對此形式較熟悉，能想像如何提問；願意參考 AI 回覆，但重視內容專業度。', '可借鏡熟悉的問答方式與他人問題，建立理解及信任。'],
      ['健康目標', '多數人不會刻意設定目標，但會好奇健康分數如何計算、如何改善。', '先幫助使用者理解自身需求，再引導持續管理。'],
      ['搜尋／引導提問', '多數人能透過提問範例，理解可以詢問哪些內容、何時適合使用 AI。', '以具體範例協助開始提問，是直接可用的設計方向。'],
    ],
    conceptNote: '這是小樣本概念測試，反映受訪者的理解與意願；不代表實際使用率、任務成功率，也不表示所有提案都已上線。',
    cohortNote: '兩輪研究包含部分重複參與者，樣本數分別呈現，不合併計算。',
    keyFinding: '多數使用者對向 AI 提問仍感到陌生，需要清晰的引導，但仍有提問與尋找資訊的需求。',
    decisionTitle: '把「可以問什麼」放在需要資訊的當下',
    decisionCopy: '綜合兩輪研究，我將優化聚焦在提問引導與服務情境。App 協助已進入 Chatbot 的使用者開始；Web 則在閱讀健康文章時，接續使用者剛產生的疑問。',
    decisions: [
      { number: '01', platform: 'APP · 建議提問', title: '從空白輸入，走向看得懂的問題起點', evidence: '第一輪訪談中，使用者表示不知道有 Chatbot，也不知道該問什麼。第二輪測試發現，看到「睡不著怎麼辦？」這類具體範例後，多數人更能理解 AI 可以提供什麼幫助。', solution: '在 App 內加入建議提問 Prompt，以具體健康問題說明服務範圍，降低自行組織第一個問題的負擔。', before: '進入 AI → 自己想問題 → 輸入', after: '進入 AI → 看見建議提問 → 開始對話', principle: '先讓使用者理解能得到什麼幫助，再邀請他提問。' },
      { number: '02', platform: 'WEB · 文章延伸問答', title: '讓提問接續閱讀，不必重新找入口', evidence: '第二輪測試顯示，多數人在沒有病痛時會先閱讀健康資訊，不一定會主動向 AI 提問；但看到熟悉的問答形式和具體問題時，更容易理解如何使用 AI。', solution: '在 Web 健康文章中加入延伸提問的 AI Chat 服務，提供貼近文章主題的建議問題，讓閱讀內容與下一步問答接在同一個情境中。', before: '閱讀文章 → 產生疑問 → 另找資訊', after: '閱讀文章 → 看見延伸問題 → AI 問答', principle: '將服務帶到需求產生的位置，延續使用者既有的資訊行為。' },
    ],
    evidenceLabel: '研究依據', solutionLabel: '設計調整', beforeLabel: '原有門檻', afterLabel: '優化方向',
    appComparison: [
      { label: 'Before', alt: '健康 2.0 App 原畫面：歡迎訊息與空白提問輸入框' },
      { label: 'After', alt: '健康 2.0 App 調整後畫面：聊天回覆下方、輸入框上方顯示可點選的建議問題' },
    ],
    scopeNote: '角色與 QA 討論版提供了理解服務的線索；本案例落地的重點是 App 建議提問與 Web 文章延伸問答。',
    uiCaption: 'Web 健康文章中的 AI 延伸問答介面',
    outcomeTitle: '成效與反思',
    outcomeCopy: 'AI Chatbot 使用量由 9k 成長至 27k。導入 AI Chatbot 的健康文章參與率最高達 88.7%，平均停留時間最高達 3 分 10 秒，分別呈現服務使用量與文章頁的互動表現。',
    metrics: [['9k → 27k', 'AI Chatbot 使用量成長'], ['88.7%', '文章參與率最高值'], ['3:10', '平均停留時間最高值']],
    metricNote: '沿用原專案成效紀錄。文章參與率不等於 AI 提問率，亦不能與 App 的 2% 直接比較；觀察結果不能單獨證明由 Chatbot 帶動。',
    reflections: [
      ['先建立理解，再談使用頻率', '兩輪研究讓我看見，功能名稱與空白輸入框不足以解釋 AI 的價值。提問範例與閱讀情境，能將抽象能力變成使用者可理解的下一步。'],
      ['引導與回答信任，需要一起處理', '第一輪對制式回答的疑慮、第二輪對內容專業度的重視，提醒我不能只關注入口。後續也應驗證答案是否實用、可理解，及能否接續使用者的疑問。'],
      ['補齊 AI 專屬的成效追蹤', '下一步追蹤入口曝光、建議問題點擊、首次提問、延伸提問與回訪，區分 App／Web 及不同文章主題，並回查統計期間與比較基準。'],
    ],
  },
  en: {
    subtitle: 'Help a health concern become a first AI question',
    intro: 'After Health 2.0 launched its App chatbot, the service accounted for only 2% of overall usage. I combined question logs, user interviews, and concept testing to understand how people perceive AI and seek health information. The research informed two directions: suggested prompts in the App and follow-up AI chat within Web articles.',
    date: '2023–2024',
    summary: [
      { label: 'User research', value: '7 in interviews\n6 in concept tests', mobileValue: '7 interviews\n6 concept tests', description: 'Two rounds to identify barriers' },
      { label: 'Solution', value: 'App prompts\nWeb article follow-up', mobileValue: 'App prompts\nWeb Q&A', description: 'Make the first question easier' },
      { label: 'Outcome', value: '9k → 27k', description: 'AI Chatbot usage growth', mobileDescription: 'Usage growth' },
    ],
    goal: 'Increase AI Chatbot\nservice usage',
    navigation: [['problem', 'Problem & data'], ['interviews', 'User interviews'], ['concept-test', 'Concept testing'], ['decisions', 'Design decisions'], ['outcomes', 'Outcomes & reflection']],
    problemTitle: 'A need for health information does not automatically become an AI question',
    problemCopy: 'Low usage was a starting signal. I examined whether inputs were complete questions, descriptions of a condition, or single symptoms. The logs revealed input patterns; interviews helped explain the reasons behind them.',
    dataInsight: 'Vague descriptions and symptom keywords made up about 54% of inputs. Many were not complete questions, suggesting an opportunity to help people express their needs. Logs alone cannot explain why others never used AI.',
    dataNote: 'Existing project logs: 20,350 events, not unique users. Rounded percentages may total slightly above 100%.',
    baselineNote: 'The 2% App service usage figure and the later Web article engagement figure measure different behaviors.',
    dataSummary: 'View question categories and event counts',
    tableHead: ['Question type', 'Input', 'Events', 'Share'],
    data: [
      ['Complete health question', 'A full sentence describing symptoms, context, or a direct question.', '8,482', '41.7%', 41.7],
      ['Vague health description', 'A condition without a clear question, such as long-term stress or poor sleep.', '6,282', '30.9%', 30.9],
      ['Health topic / symptom keyword', 'Only a disease or symptom name, such as headache or diabetes.', '4,683', '23.0%', 23],
      ['Unrelated text', 'Greetings, thanks, casual conversation, or unrelated content.', '791', '3.9%', 3.9],
      ['Blank input', 'No content entered.', '112', '0.6%', .6],
    ],
    interviewTitle: 'Understand health behavior, then identify expectations and concerns about AI',
    interviewCopy: 'The first round covered different health conditions and approaches to health promotion. Feedback on the existing chatbot revealed three distinct issues: awareness, starting a question, and trust in the response. These informed the next round of concept exploration.',
    timeline: [['Nov 17–20', 'Recruit'], ['Nov 20–24', 'Interview'], ['Nov 27–Dec 1', 'Synthesize']],
    interviewMeta: [['When', 'November 2023'], ['Participants', '7 people, ages 35–68'], ['Behavior', '3 proactive / 4 passive'], ['Health status', '2 healthy / 2 subhealthy / 3 with illness']],
    interviewLabel: 'Interview summaries',
    interviewFindings: [
      ['AI can fill an availability gap', 'A participant saw value in asking AI late at night when a person was unavailable.', 'Opportunity: provide an accessible entry to information when a question arises.'],
      ['The entry and question scope are unclear', 'Feedback included not knowing the feature existed, what to ask, or what an AI chatbot / ChatGPT was.', 'Barrier: explain the service and offer a concrete starting point.'],
      ['Response quality affects trust', 'A participant with prior experience found answers formulaic and preferred asking a person.', 'Constraint: useful, credible responses matter alongside easier entry.'],
    ],
    researchBridge: 'Next question: would specific roles, example prompts, or familiar Q&A formats help people understand what AI could do for them?',
    conceptTitle: 'Compare service formats to find an understandable starting point',
    conceptCopy: 'The second round used prototypes and interviews to explore acceptance, expected uses, and feedback on personal health management concepts. It covered records, reminders, proactive care, AI roles, group chat, Q&A, health goals, and search / question entry points.',
    conceptMeta: [['When', 'Jan 13–23, 2024'], ['Participants', '6 people, ages 37–68'], ['Health status', '3 subhealthy / 3 with illness'], ['Product experience', '3 App users / 3 non-users']],
    conceptTableHead: ['Tested format', 'User feedback', 'Design implication'],
    concepts: [
      ['Personal records, reminders & care', 'People without a recording habit would not start just because chat made it easier. Practical improvements mattered more than caring messages.', 'Show useful information first; convenience alone is not motivation.'],
      ['Different AI roles', 'Most could understand services from role names and descriptions, and expected relevant exercise or recipe recommendations.', 'Specific uses clarify the service but also set expectations for proactive help.'],
      ['Topic group chat + AI', 'Most showed little interest in group chat, preferred reading discussions, and questioned their expertise.', 'Joining a conversation should not be required to find information.'],
      ['Q&A board + AI', 'The report describes all six as more familiar with Q&A and able to imagine asking. They would consider AI answers but valued expertise.', 'Familiar questions and answers can help people understand the service.'],
      ['Health goals', 'Most did not deliberately set goals but were curious about health scores and how to improve them.', 'Help people understand a need before inviting ongoing management.'],
      ['Search / guided questions', 'Most understood what to ask AI and when to use it through example questions.', 'Concrete prompts offer an actionable way to support the first question.'],
    ],
    conceptNote: 'This small concept test describes understanding and stated interest, not actual adoption or task success. Not every tested proposal shipped.',
    cohortNote: 'Some participants took part in both rounds. Sample sizes are reported separately rather than combined.',
    keyFinding: 'Most users were still unfamiliar with asking AI and needed clear guidance, while retaining a need to ask questions and find information.',
    decisionTitle: 'Show what to ask when information is needed',
    decisionCopy: 'Across both rounds, I focused on question guidance and context. In the App, help people who have entered the chatbot begin. On the Web, connect questions to the health article they are already reading.',
    decisions: [
      { number: '01', platform: 'APP · SUGGESTED PROMPTS', title: 'Give a blank input a concrete starting point', evidence: 'In round one, participants said they did not know what to ask. In round two, concrete examples such as “What can I do when I cannot sleep?” helped most participants understand how AI could help.', solution: 'Add suggested health questions within the App to explain service scope and reduce the effort of composing a first question.', before: 'Enter AI → Think of a question → Type', after: 'Enter AI → See suggested prompts → Start', principle: 'Explain the help available before inviting a question.' },
      { number: '02', platform: 'WEB · ARTICLE FOLLOW-UP', title: 'Let a question continue the reading journey', evidence: 'Round two showed that people often read health information passively when they were not in pain. Familiar Q&A formats and concrete questions made it easier to understand when and how to use AI.', solution: 'Add follow-up AI chat within Web health articles, with questions related to the article topic, connecting reading and Q&A in one context.', before: 'Read → Have a question → Search elsewhere', after: 'Read → See related questions → Ask AI', principle: 'Bring the service to the moment a need arises.' },
    ],
    evidenceLabel: 'Research evidence', solutionLabel: 'Design response', beforeLabel: 'Existing barrier', afterLabel: 'Design direction',
    appComparison: [
      { label: 'Before', alt: 'Original Health 2.0 App chatbot with welcome messages and a blank question input' },
      { label: 'After', alt: 'Updated Health 2.0 App chatbot with selectable questions below the reply and above the input' },
    ],
    scopeNote: 'AI roles and Q&A boards informed service clarity. This case implements App prompts and Web article follow-up chat.',
    uiCaption: 'AI follow-up chat within Web health articles',
    outcomeTitle: 'Service usage growth and article engagement',
    outcomeCopy: 'AI Chatbot usage grew from 9k to 27k. Articles with the chatbot recorded engagement as high as 88.7% and average dwell time as high as 3 minutes 10 seconds. These figures separately describe service usage and article-page behavior.',
    metrics: [['9k → 27k', 'AI Chatbot usage growth'], ['88.7%', 'Highest article engagement'], ['3:10', 'Highest average dwell time']],
    metricNote: 'Figures retained from existing project records. Article engagement is not AI question rate and cannot be compared directly with the App’s 2%. Observation alone does not establish that the chatbot caused the result.',
    reflections: [
      ['Build understanding before frequency', 'Both rounds showed that a feature name and blank input do not explain AI’s value. Examples and reading context translate abstract capability into an understandable next step.'],
      ['Support entry and response trust together', 'Formulaic-answer concerns and the emphasis on expertise mean entry alone is insufficient. Next, test whether answers are useful, understandable, and able to support follow-up questions.'],
      ['Measure AI use directly', 'Track entry exposure, prompt clicks, first questions, follow-up questions, and return visits by App / Web and article topic. Confirm reporting periods and comparison baselines.'],
    ],
  },
}
